version: "3.9"

services:
  front:
    container_name: frontend
    image: registry.hiriko.local:5000/front:${TAG_FRONT}
    ports:
      - "3000:3000"

networks:
  default:
    external: true
    name: deploy_back_theatre
